version: '3'
services:
  eth:
    build:
      context: .
      dockerfile: ./docker/images/eth/Dockerfile
    volumes:
      - ./docker/data/eth:/root/private_net:cached
    ports:
      - 8545:8545
      - 30303:30303
    tty: true
    networks:
      default:
      sckit-network:
  sol:
    build:
      context: .
      dockerfile: ./docker/images/sol/Dockerfile
    env_file: ./.env
    entrypoint: npm run watch:sol
    volumes:
      - ./:/projects/sckit:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    networks:
      default:
      sckit-network:
  web:
    build:
      context: .
      dockerfile: ./docker/images/web/Dockerfile
    command: npm run start
    env_file: ./.env
    volumes:
      - ./:/projects/sckit:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 32334:3000
    networks:
      default:
      sckit-network:
networks:
  sckit-network:
    external: true